[font]
size = 7

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[scrolling]
history = 1000

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 4
y = 4
