"generic options/vim variables
runtime myconfig/options.vim

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" PLUGIN configuration

"list of plugins:
runtime myconfig/plugins.vim

"config per plugin:
runtime myconfig/autopairs.vim
runtime myconfig/coc.vim
runtime myconfig/emmet.vim
runtime myconfig/lightline.vim
runtime myconfig/minibuf.vim
runtime myconfig/nerdtree.vim
runtime myconfig/tagbar.vim
runtime myconfig/vim-go.vim
colorscheme gruvbox
